import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Header from "components/Header";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <section className="mt-10">
        <div className="bg-black mx-6 md:mx-16 rounded-2xl text-white text-center ">
          <div className="pt-20 md:pt-28 ">
            <h1 className="font-bold text-4xl">iPhone 14 Pro</h1>
            <p className="mt-4 text-xl">Semakin Pro.</p>
            <div className="hidden md:flex justify-center mt-32">
              <img src={"/images/iphone14.png"} alt="" className="w-3/5" />
            </div>
            <div className="flex justify-center mt-20 md:hidden">
              <img src={"/images/iphone14_2.png"} alt="" className="w-3/5" />
            </div>
          </div>
        </div>
      </section>

      <section className="my-20 mx-16">
        <div className="flex justify-around">
          {/* Content Left */}
          <div className="h-[80vh] rounded-2xl w-[76.2%] flex justify-center">
            <iframe
              className=" rounded-2xl w-full h-full"
              src="https://www.youtube.com/embed/FT3ODSg1GFE"
              title="YouTube video player"
              frameborder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture;"
              allowfullscreen
            ></iframe>
          </div>
          {/* content right */}
          <div className="flex flex-col justify-between w-[20%]">
            {/* Top */}
            <div className="relative bg-black h-[38vh] rounded-xl flex flex-col justify-evenly">
              <img
                src={"/images/airpods.png"}
                alt=""
                className="absolute w-60 self-center"
              />
              <a
                href=""
                className="flex flex-1 z-10 items-end hover:translate-x-8 hover:ease-in-out hover:transition-all text-white hover:text-white"
              >
                <div className="flex absolute -left-6 bottom-3 items-center ">
                  <span class="material-icons">arrow_forward</span>
                  <h1 className="text-white ml-3 text-xl font-semibold">
                    Accessories
                  </h1>
                </div>
              </a>
            </div>
            {/* bottom */}
            <div className="relative bg-black h-[38vh] rounded-xl flex flex-col justify-evenly">
              <img
                src={"/images/ecatalog.png"}
                alt=""
                className="absolute w-44 self-center"
              />
              <a
                href=""
                className="flex flex-1 z-10 items-end hover:translate-x-8 hover:ease-in-out hover:transition-all text-white hover:text-white"
              >
                <div className="flex absolute -left-6 bottom-3 items-center ">
                  <span class="material-icons">arrow_forward</span>
                  <h1 className="text-white ml-3 text-xl font-semibold">
                    e-Catalog
                  </h1>
                </div>
              </a>
            </div>
          </div>
        </div>
      </section>

      <div className="flex rounded-xl my-20 items-center mx-20 bg-black py-8 text-white/90 justify-center">
        {/* <div className="flex space-x-2 ">
          <h1 className="text-3xl font-semibold">Features</h1>
          <span class="material-icons text-3xl font-semibold">
            arrow_forward
          </span>
        </div> */}
        <div className="flex items-center space-x-4">
          <span class="material-icons-outlined text-7xl">verified_user</span>
          <div className="space-y-2">
            <h3 className="text-lg font-bold">Garansi Resmi</h3>
            <p className="text-sm">Produk Bergaransi Resmi / Garansi TAM</p>
          </div>
        </div>

        <div className="flex items-center space-x-4">
          <span class="material-icons-outlined text-7xl">support_agent</span>
          <div className="space-y-2">
            <h3 className="text-lg font-bold ">Layanan Pelanggan</h3>
            <p className="text-sm">Tim Kami Siap Membantu Seputar Produk</p>
          </div>
        </div>

        <div className="flex items-center space-x-4">
          <span class="material-icons-outlined text-7xl">local_shipping</span>
          <div className="space-y-2">
            <h3 className="text-lg font-bold">Jasa Pengiriman</h3>
            <p className="text-sm">Pengiriman Dan Keamanan Terpercaya</p>
          </div>
        </div>

        <div className="flex items-center space-x-4">
          <span class="material-icons-outlined text-7xl">discount</span>
          <div className="space-y-2">
            <h3 className="text-lg font-bold">Keuntungan Belanja</h3>
            <p className="w-3/4 text-sm">
              Promo dan Info Terkini Produk Gadget Terbaru
            </p>
          </div>
        </div>
        <div className="flex"></div>
      </div>
    </>
  );
}
